version: 2
run:
  timeout: 5m
  go: "1.25"
linters:
  enable:
    - gosec
    - staticcheck
    - wsl_v5
    - nlreturn
    - errcheck
    - dupl
    - gocyclo
    - whitespace
    - tagalign
  settings:
    gocyclo:
      min-complexity: 20
    dupl:
      threshold: 200
    wsl_v5:
      allow-cuddle-declarations: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      allow-separated-leading-comment: true
    gosec:
      excludes:
        - G115
issues:
  exclude-use-default: false
