version: 2
run:
  timeout: 5m
  go: "1.25"
linters:
  enable:
    - gosec
    - staticcheck
    - wsl
    - nlreturn
    - errcheck
    - dupl
    - gocyclo
    - whitespace
    - tagalign
  settings:
    gocyclo:
      min-complexity: 20
    dupl:
      threshold: 200
    gosec:
      excludes:
        - G115
issues:
  exclude-use-default: false
