version: 2
run:
  timeout: 5m
  go: "1.25"
linters:
  enable:
    - gosec
    - staticcheck
    - wsl_v5
    - nlreturn
    - errcheck
    - dupl
    - gocyclo
    - whitespace
    - tagalign
linters-settings:
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
  gosec:
    excludes:
      - G115
issues:
  exclude-use-default: false
