version: 2
run:
  timeout: 5m
  go: "1.24"
linters:
  enable:
    - gosec
    - staticcheck
    - wsl
    - nlreturn
    - errcheck
    - dupl
    - gocyclo
    - whitespace
    - tagalign
linters-settings:
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-separated-leading-comment: true
  gosec:
    excludes:
      - G115
issues:
  exclude-use-default: false
