version: 2
run:
  timeout: 5m
  go: "1.25"
linters:
  enable:
    - gosec
    - staticcheck
    - wsl_v5
    - nlreturn
    - errcheck
    - dupl
    - gocyclo
    - whitespace
    - tagalign
  settings:
    gocyclo:
      min-complexity: 20
    dupl:
      threshold: 200
    wsl_v5:
      default: "default"
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      case-max-lines: 0
    gosec:
      excludes:
        - G115
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  whole-files: false
